spring:
  datasource:
    url: jdbc:mysql://petshield-dev.c344wgygm0ss.ap-northeast-2.rds.amazonaws.com:3306/petshield
    username: root
    password: han3546*
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

server:
  port: 8080  # 기본 HTTP 포트로 설정
