spring:
  datasource:
    url: ${AWS_DB_URL}
    username: ${AWS_DB_USER}
    password: ${AWS_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
    # 'mvc' 관련 설정은 보안 설정에 직접적으로 영향을 미치지 않으므로 보안 설정에 포함시키지 않습니다.

  application:
    name: PetShield

swagger:
  ui:
    base-url: /swagger-ui/  # Swagger UI의 기본 경로 설정

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  client_secret: ${KAKAO_CLIENT_SECRET}
  redirect_uri: http://localhost:8080/callback
  token_uri: https://kauth.kakao.com/oauth/token
  user_info_uri: https://kapi.kakao.com/v2/user/me

server:
  port: 8080  # 기본 HTTP 포트 설정


